import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import StoreProvider from "@/app/StoreProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <StoreProvider>

            <Navbar/>
            {children}
        </StoreProvider>

        </body>
        </html>

    );
}
